### ISSUE TITLE
pretrained checkpoint

### ISSUE THREAD

**Issue by eschmidbauer** [winddori2002/DEX-TTS#1]
thank you for sharing this project! I would like to try inference using this repo. Do you have a pretrained checkpoint available?

**Comment by winddori2002** [comment]
Hi, Thanks for your interests.

I am currently redesigning a pipeline to be compatible with multi-GPU training and the LibriTTS dataset.
I will upload a checkpoint soon.

**Comment by eschmidbauer** [comment]
I see you shared the model [weights](https://github.com/winddori2002/DEX-TTS/releases/download/weights/GeDEXTTS_weight_ljs.zip) trained on LJSpeech dataset
Thank you!
