### ISSUE TITLE
Probably the inconsistency between paper and the code?

### ISSUE THREAD

**Issue by yusuke-ai** [winddori2002/DEX-TTS#7]
Hi,

Thank you for the awesome work!

I'm reading your paper and the code. And maybe it has some inconsistency?
The paper says
> T-V encoder contains a few residual convolution blocks, but we employ Layer Normalization (LN) instead of IN to preserve temporal relationships in each instance

but the code below doesn't contain such code.
https://github.com/winddori2002/DEX-TTS/blob/main/DEX-TTS/model/ref_encoder.py#L131

Should I add layer normalization to the code or is it ok to leave it without LN?

Thank you!

**Comment by winddori2002** [comment]
Hi, thanks for your interest.

For TV encoder, replacing BN in the TVEncoderBlock with LN worked better. 
You can check the TVEncoderBlock and  BasicConv class.

**Comment by yusuke-ai** [comment]
Thank you for the reply!
OK. I will check.
